print("*******************************************")
print("PROGRAMA QUE ABRE, LEE, IMPRIME ARCHIVO TXT")
print("*******************************************")
archivo=open("C:\Users\VIVELAB\Downloads\chavo.txt")
archivo.close()